apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cf-stack-operator
rules:
  - apiGroups:
      - cloudformation.mdstechinc.com
    resources:
      - stacks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudformation.mdstechinc.com
    resources:
      - stacks/finalizers
    verbs:
      - update
  - apiGroups:
      - cloudformation.mdstechinc.com
    resources:
      - stacks/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-stack-operator
  namespace: cf-stack-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cf-stack-operator
subjects:
  - kind: ServiceAccount
    name: cf-stack-operator
    namespace: cf-stack-operator
roleRef:
  kind: ClusterRole
  name: cf-stack-operator
  apiGroup: ""